language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: 
  app: glacial-refuge-72490
  on:
    repo: Shubanshii/react-trello-testing
