language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: TvwW8bbw1Wknr2rt12qU7zxnUEzdzJlI/NLF7DMToVDpnagQE68JAPrsjyGwWqyiWvQBKTlokOlcyjlGdlz64Be/BE8sUrNiyrFAyjIpqks7c69p+nOqCpFj6ypeRBUXgEeRtGi8hOQscaNxZoY95W/6v/VLUG3HX3apDYt+g6KqUOssgDATW11bE+ZPQ1zVgFLHB+g9b0CQYr8CRLsRX2qbhg/PiqNhNC+UcNzqPbjQtSAhe4R0m5bsn5gWnbXluZ3+BcQtXqkXTuGLX3blWh1O5ys8Du2u8kyVQ/yhh5oZwar/g8UG/a+3HPjMYwinvOmDvgnfdKx/gRyntrLUWuH/R3H6EaFmQuN0X23bLmmhudxHX5LXSTQDXn6nIEZ3TNg1P55M58acbSOsaKzqZbPZoK/aIdrmpZyC7oKolXccq6+WO1MT4gaxmaMoArF0CNefuSTT+S9ELm8G72uS4BfdOQgIpkRwWySORKhUNUUrZjcPG3LZ7FNhHwVn1OR7hAN6k+1F6WNAgfoaw5VDEBSzXTzqbF376Ze/CbcBo4NWRRUCJBN2SQHYImdl7ROLaL+6bTGmB0+1/j9RqiTMYURI4dK7shE8Os5TDAW5SHOdj3u3eGkRhSdMz1GmZTELUiDbNW7+Y4IRTlDlFHEbhd3wky3A7qw3SeC63gh4+Vw=
  app: glacial-refuge-72490
  on:
    repo: Shubanshii/react-trello-testing
