language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: 61bda477-0e5e-48f2-b1e7-fe5dc3ba5e19
  app: glacial-refuge-72490
  on:
    repo: Shubanshii/react-trello-testing
